### ISSUE TITLE
pywps-demo, service error: unable to open database file

### ISSUE THREAD

**Issue by suryakant54321** [geopython/pywps-demo#28]
I am able to execute GetCapabilities and DescribeProcess requests.
for Execute request I get following error

OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file

- operating system: Ubuntu 16.04 (UbuntuGIS 10)
- Python version: 2.7.12
- PyWPS version: 4.0.0
- source/distribution
 - [x] git clone

- web server
 - [x] Apache/mod_wsgi

# Steps to Reproduce
http://localhost:5000/wps?request=Execute&service=WPS&identifier=say_hello&version=1.0.0&datainputs=name=someName

# Additional Information
wps log
2017-04-20 00:22:50,897] [INFO] file=/usr/local/lib/python2.7/dist-packages/pywps-4.0.0-py2.7.egg/pywps/app/Service.py line=567 module=Service function=__call__ Request: execute

2017-04-20 00:22:50,975] [ERROR] file=/usr/local/lib/python2.7/dist-packages/pywps-4.0.0-py2.7.egg/pywps/exceptions.py line=45 module=exceptions function=__init__ Exception: code: 400, locator: Service error: (pysqlite2.dbapi2.OperationalError) unable to open database file, description:

**Comment by ldesousa** [comment]
This is a bug with the PyWPS library itself, already reported here:
https://github.com/geopython/pywps/issues/244

In the meantime, I suggest you use a different database management system, such as Postgres. An example connection string:
database=postgresql://pywps:toto123@localhost:5432/pywps-demo

You just need to create the user and database beforehand (in the string above they are pywps and pywps-demo).

Thanks for reporting in any case.

**Comment by mlacayoemery** [comment]
Another option would be to change the database line to the following:

`sqlite:///:memory:`

**Comment by dahaynes** [comment]
I'm running into this error trying to move WebPySAL into a production environment. I don't seem to be able to the wps.cfg file to create a new database connection.
